---
title: "Yummly project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##loading Libraries

```{r}
library(jsonlite)
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(reshape2)
```
## loading Data 

```{r}
setwd("C:/Users/Bimal/Desktop/Data Science/Slide Rule/Yummly Data")
train_data <- fromJSON(txt = "train.json",flatten = TRUE)
train <- tbl_df(train_data)
train
nrow(train)

```

## Freq of cuisines

```{r, echo=FALSE}
ggplot(train,aes(cuisine)) + geom_bar()
```

```{r}
train_cuisine_sum <- train %>% 
            group_by(cuisine) %>% 
              summarise(number = n()) %>% 
                arrange(number)
train_cuisine_sum
```

# Ingredients Analysis
```{r}
# Ingredients 
x <- rbind(train$ingredients)
unique_ingredients <- data_frame(unique(sort(unlist(train$ingredients))))
unique_ingredients

```
# Using Corpus
```{r}
library(tm)
ingredients <- Corpus(VectorSource(train$ingredients))
ingredients
ingredients <- tm_map(ingredients, removeNumbers)
removeBrackets <- content_transformer(function(x){gsub(pattern = "\\(|\\)|,",replacement = " ",x)})
ingredients <- tm_map(ingredients,removeBrackets)
ingredients <- tm_map(ingredients,removePunctuation)
ingredients <- tm_map(ingredients, stemDocument)
ingredients <- tm_map(ingredients, stripWhitespace)

ingredientsMatirx <- DocumentTermMatrix(ingredients)
ingredientsMatirx

#Converting Corpus matrix into df
ingredientsDTM <- as.data.frame(as.matrix(ingredientsMatirx))
str(ingredientsDTM)

#adding DTM back to train data frame
train_new <- data.frame(train,ingredientsDTM) 

str(train_new)

x <- filter(train_new,train_new$apple==1)
x[1:2]

```
# Applying SVD 
```{r}
# creating the variable matrix
train_SVD_data <- train_new %>% arrange(cuisine) %>% select(5:ncol(train_new)) 
str(train_SVD_data)

train_SVD <- svd(train_SVD_data)
d <- train_SVD$d
u <- train_SVD$u
v <- train_SVD$v  
top_n(x = data.frame(d),n = 100)
```
